(function(c){c.jScrollPane={active:[]};c.fn.jScrollPane=function(a){a=c.extend({},c.fn.jScrollPane.defaults,a);return this.each(function(){var d=c(this),k=0,o,f,p,E=a.topCapHeight,g;if(c(this).parent().is(".jScrollPaneContainer")){g=c(this).parent();k=a.maintainPosition?d.position().top:0;var h=c(this).parent();o=h.innerWidth();f=h.outerHeight();h.unmousewheel&&h.unmousewheel();c(">.jScrollPaneTrack, >.jScrollArrowUp, >.jScrollArrowDown, >.jScrollCap",h).remove();d.css({top:0})}else{d.data("originalStyleTag",
d.attr("style"));d.css("overflow","hidden");this.originalPadding=d.css("paddingTop")+" "+d.css("paddingRight")+" "+d.css("paddingBottom")+" "+d.css("paddingLeft");this.originalSidePaddingTotal=(parseInt(d.css("paddingLeft"))||0)+(parseInt(d.css("paddingRight"))||0);o=d.parent().innerWidth();f=d.parent().innerHeight();g=c("<div></div>").attr({className:"jScrollPaneContainer"}).css({height:"100%",width:"100%"});a.enableKeyboardNavigation&&g.attr("tabindex",a.tabIndex);d.wrap(g);g=d.parent();c(document).bind("emchange",
function(){d.jScrollPane(a)})}p=f;h={height:"auto",width:"100%"};if(a.scrollbarOnLeft)h.paddingLeft=a.scrollbarMargin+a.scrollbarWidth+"px";else h.paddingRight=a.scrollbarMargin+"px";d.css(h);d.parent().outerHeight();var q=d.outerHeight(),t=f/q;h=t<0.99;g[h?"addClass":"removeClass"]("jScrollPaneScrollable");if(h){g.append(c("<div></div>").addClass("jScrollCap jScrollCapTop").css({height:a.topCapHeight}),c("<div></div>").attr({className:"jScrollPaneTrack"}).css({width:a.scrollbarWidth+"px"}).append(c("<div></div>").attr({className:"jScrollPaneDrag"}).css({width:a.scrollbarWidth+
"px"}).append(c("<div></div>").attr({className:"jScrollPaneDragTop"}).css({width:a.scrollbarWidth+"px"}),c("<div></div>").attr({className:"jScrollPaneDragBottom"}).css({width:a.scrollbarWidth+"px"}))),c("<div></div>").addClass("jScrollCap jScrollCapBottom").css({height:a.bottomCapHeight}));o=c(">.jScrollPaneTrack",g);var y=c(">.jScrollPaneTrack .jScrollPaneDrag",g),z,l=[],r,u=function(){if(r>4||r%4==0)m(j+z*A);r++};a.enableKeyboardNavigation&&g.bind("keydown.jscrollpane",function(b){switch(b.keyCode){case 38:z=
-1;r=0;u();l[l.length]=setInterval(u,100);return false;case 40:z=1;r=0;u();l[l.length]=setInterval(u,100);return false;case 33:case 34:return false;default:}}).bind("keyup.jscrollpane",function(b){if(b.keyCode==38||b.keyCode==40){for(b=0;b<l.length;b++)clearInterval(l[b]);return false}});if(a.arrowSize){p=f-a.arrowSize-a.arrowSize;E+=a.arrowSize}p-=a.topCapHeight+a.bottomCapHeight;o.css({height:p+"px",top:E+"px"});var B=c(this).css({position:"absolute",overflow:"visible"}),C,n,A,j=0,F=t*f/2,G=function(b,
e){var i=e=="X"?"Left":"Top";return b["page"+e]||b["client"+e]+(document.documentElement["scroll"+i]||document.body["scroll"+i])||0},H=function(){return false},I=function(){v();C=y.offset(false);C.top-=j;n=p-y[0].offsetHeight;A=2*a.wheelSpeed*n/q},J=function(){c("html").unbind("mouseup",J).unbind("mousemove",K);F=t*f/2;c.browser.msie&&c("html").unbind("dragstart",H).unbind("selectstart",H)},m=function(b){g.scrollTop(0);j=b=b<0?0:b>n?n:b;y.css({top:b+"px"});b=b/n;d.data("jScrollPanePosition",(f-q)*
-b);B.css({top:(f-q)*b+"px"});d.trigger("scroll")},K=function(b){m(G(b,"Y")-C.top-F)};Math.max(Math.min(t*(f-a.arrowSize*2),a.dragMaxHeight),a.dragMinHeight);var L,M=function(){clearInterval(L);c("html").unbind("mouseup",M).unbind("mousemove",N)},N=function(b){G(b,"Y")};g.bind("mousewheel",function(b,e){e=e||(b.wheelDelta?b.wheelDelta/120:b.detail?-b.detail/3:0);I();v();b=j;m(j-e*A);return b==j});var w,D;function O(){var b=(w-j)/a.animateStep;if(b>1||b<-1)m(j+b);else{m(w);v()}}var v=function(){if(D){clearInterval(D);
delete w}},s=function(b,e){if(typeof b=="string"){try{$e=c(b,d)}catch(i){return}if(!$e.length)return;b=$e.offset().top-d.offset().top}v();var x=q-f;b=b>x?x:b;d.data("jScrollPaneMaxScroll",x);b=b/x*n;if(e||!a.animateTo)m(b);else{g.scrollTop(0);w=b;D=setInterval(O,a.animateInterval)}};d[0].scrollTo=s;d[0].scrollBy=function(b){var e=-parseInt(B.css("top"))||0;s(e+b)};I();s(-k,true);c("*",this).bind("focus",function(){for(var b=c(this),e=0,i=100;b[0]!=d[0];){e+=b.position().top;b=b.offsetParent();if(!i--)return}b=
-parseInt(B.css("top"))||0;i=b+f;if(!(e>b&&e<i)){i=e-a.scrollbarMargin;if(e>b)i+=c(this).height()+15+a.scrollbarMargin-f;s(i)}});if(a.observeHash)if(location.hash&&location.hash.length>1)setTimeout(function(){s(location.hash)},c.browser.safari?100:0);c.jScrollPane.active.push(d[0])}else{d.css({height:f+"px",width:o-this.originalSidePaddingTotal+"px",padding:this.originalPadding});d[0].scrollTo=d[0].scrollBy=function(){}}})};c.fn.jScrollPaneRemove=function(){c(this).each(function(){$this=c(this);var a=
$this.parent();if(a.is(".jScrollPaneContainer")){$this.css({top:"",height:"",width:"",padding:"",overflow:"",position:""});$this.attr("style",$this.data("originalStyleTag"));a.after($this).remove()}})};c.fn.jScrollPane.defaults={scrollbarWidth:15,scrollbarMargin:5,wheelSpeed:18,showArrows:false,arrowSize:0,animateTo:false,dragMinHeight:137,dragMaxHeight:99999,animateInterval:100,animateStep:3,maintainPosition:true,scrollbarOnLeft:false,reinitialiseOnImageLoad:false,tabIndex:0,enableKeyboardNavigation:true,
animateToInternalLinks:false,topCapHeight:20,bottomCapHeight:20,observeHash:true};c(window).bind("unload",function(){for(var a=c.jScrollPane.active,d=0;d<a.length;d++)a[d].scrollTo=a[d].scrollBy=null})})(jQuery);
(function(c){c.event.special.mousewheel={setup:function(){var a=c.event.special.mousewheel.handler;c.browser.mozilla&&c(this).bind("mousemove.mousewheel",function(d){c.data(this,"mwcursorposdata",{pageX:d.pageX,pageY:d.pageY,clientX:d.clientX,clientY:d.clientY})});if(this.addEventListener)this.addEventListener(c.browser.mozilla?"DOMMouseScroll":"mousewheel",a,false);else this.onmousewheel=a},teardown:function(){var a=c.event.special.mousewheel.handler;c(this).unbind("mousemove.mousewheel");if(this.removeEventListener)this.removeEventListener(c.browser.mozilla?
"DOMMouseScroll":"mousewheel",a,false);else this.onmousewheel=function(){};c.removeData(this,"mwcursorposdata")},handler:function(a){var d=Array.prototype.slice.call(arguments,1);a=c.event.fix(a||window.event);c.extend(a,c.data(this,"mwcursorposdata")||{});var k=0;if(a.wheelDelta)k=a.wheelDelta/120;if(a.detail)k=-a.detail/3;a.data=a.data||{};a.type="mousewheel";d.unshift(k);d.unshift(a);return c.event.handle.apply(this,d)}};c.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},
unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
